forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-package',
  :git => "https://github.com/puppetlabs/puppetlabs-package.git"

mod 'puppetlabs-service',
  :git => "https://github.com/puppetlabs/puppetlabs-service.git"
